set(BEE_VERSION_MAJOR 0)
set(BEE_VERSION_MINOR 0)
set(BEE_VERSION_PATCH 0)

set(BEE_VERSION "${BEE_VERSION_MAJOR}.${BEE_VERSION_MINOR}.${BEE_VERSION_PATCH}")

add_definitions(-DBEE_VERSION="${BEE_VERSION}")